version: '3'
services:

  backend:
    image: ticmas-backend
    ports:
      - "5000:5000"
    
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
